### ISSUE TITLE
Возможность выбрать способ отправки чека в заказах оплачиваемых через API

### ISSUE THREAD

**Issue by Kamaew** [iiko/front.api.sdk#149]
Добрый день. По документации https://iiko.github.io/front.api.doc/2019/11/25/cheque-info-on-navigating-to-payment.html
Можно задать почту для отправки чека на почту при событии OnNavigatingToPaymentScreen . 

Как это сделать если не вызывается событие OnNavigatingToPaymentScreen вообще. 

То есть заказ создается через api  (editSession.CreateOrder)
и 
оплачивается через api  (PluginContext.Operations.PayOrder)

**Comment by Kamaew** [comment]
@iikoAPI  ?

**Comment by iikoAPI** [comment]
Hi iiko/front.api.sdk,We would like to acknowledge that we have received your request and a ticket has been created.A support representative will be reviewing your request and will send you a personal response.Thank you for your patience.Sincerely,Support Team[#ID-62281117]Sunday, July 5, 2020 10:42 PM, Kamaew:
@iikoAPI  ?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/iiko/front.api.sdk/issues/149#issuecomment-654026498",
"url": "https://github.com/iiko/front.api.sdk/issues/149#issuecomment-654026498",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by letolika** [comment]
Добрый день!
Спасибо за заявку. Если навигации на кассу не было, действительно нельзя указать способ отправки чека для оплаты заказа. Можно только для [предоплаты](https://iiko.github.io/front.api.sdk/v7/html/M_Resto_Front_Api_IOperationService_ProcessPrepay.htm). Исправим (задача RMS-51391).

**Comment by iikoAPI** [comment]
Hi iiko/front.api.sdk,We would like to acknowledge that we have received your request and a ticket has been created.A support representative will be reviewing your request and will send you a personal response.Thank you for your patience.Sincerely,Support Team[#ID-62286814]Monday, July 6, 2020 12:04 AM, letolika:
Closed #149.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/iiko/front.api.sdk/issues/149#event-3514506353",
"url": "https://github.com/iiko/front.api.sdk/issues/149#event-3514506353",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by iikoAPI** [comment]
Добрый день, iiko/front.api.sdk!Мы получили ваше письмо и создали заявку.Сотрудник службы поддержки рассмотрит ваш запрос и ответит вам в ближайшее время.[#ID-62286822]6 июля 2020 г. 0:04, letolika:
Добрый день!
Спасибо за заявку. Если навигации на кассу не было, действительно нельзя указать способ отправки чека для оплаты заказа. Можно только для предоплаты. Исправим (задача RMS-51391).

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/iiko/front.api.sdk/issues/149#issuecomment-654054238",
"url": "https://github.com/iiko/front.api.sdk/issues/149#issuecomment-654054238",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by letolika** [comment]
[Готово.](https://iiko.github.io/front.api.doc/2020/07/23/cheque-info-on-order-pay.html)

**Comment by iikoAPI** [comment]
Hi iiko/front.api.sdk,We would like to acknowledge that we have received your request and a ticket has been created.A support representative will be reviewing your request and will send you a personal response.Thank you for your patience.Sincerely,Support Team[#ID-63391368]23 июля 2020 г. 0:00, letolika:

Готово.



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/iiko/front.api.sdk/issues/149#issuecomment-662849787",

"url": "https://github.com/iiko/front.api.sdk/issues/149#issuecomment-662849787",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by iikoAPI** [comment]
​​​​​​​​​​
Dear iiko/front.api.sdk,

Your ticket ${Проблема} -  has been closed.

We hope that the ticket was resolved to your satisfaction. If you feel that the ticket should not be closed or if the ticket has not been resolved, please reply to this email.

Sincerely,
Support Team

[#ID-62281117]

**Comment by iikoAPI** [comment]
​​​​​​​​​​
Dear iiko/front.api.sdk,

Your ticket ${Проблема} -  has been closed.

We hope that the ticket was resolved to your satisfaction. If you feel that the ticket should not be closed or if the ticket has not been resolved, please reply to this email.

Sincerely,
Support Team

[#ID-62286814]

**Comment by iikoAPI** [comment]
​​​​​​​​​​
Здравствуйте, iiko/front.api.sdk!Ваша заявка успешно выполнена! Оцените, пожалуйста, выполнение вашей заявкиМы надеемся, что вы удовлетворены решением проблемы. Если вы считаете, что проблема была решена не полностью, пожалуйста ответьте на это письмо.

[#ID-62286822]

**Comment by iikoAPI** [comment]
​​​​​​​​​​
Dear iiko/front.api.sdk,

Your ticket ${Проблема} -  has been closed.

We hope that the ticket was resolved to your satisfaction. If you feel that the ticket should not be closed or if the ticket has not been resolved, please reply to this email.

Sincerely,
Support Team

[#ID-63391368]

**Comment by rgalk** [comment]
test test

________________________________
От: iikoAPI ***@***.***>
Отправлено: 31 мая 2023 г. 13:27
Кому: iiko/front.api.sdk ***@***.***>
Копия: Subscribed ***@***.***>
Тема: Re: [iiko/front.api.sdk] Возможность выбрать способ отправки чека в заказах оплачиваемых через API (#149)


​​​​​​​​​​
Dear iiko/front.api.sdk,

Your ticket ${Проблема} - has been closed.

We hope that the ticket was resolved to your satisfaction. If you feel that the ticket should not be closed or if the ticket has not been resolved, please reply to this email.

Sincerely,
Support Team

[#ID-63391368]
