### ISSUE TITLE
Удалить заказ. Need all cafe sessions be opened

### ISSUE THREAD

**Issue by novg** [iiko/front.api.sdk#160]
Добрый день.
SDK - Resto.Front.Api.V5
Создал заказ. Добавил к нему продукт.

Сейчас при удалении заказа вылетает ошибка:

`[2020-09-03 13:27:41,006]  INFO [11] - Deleting order error: Resto.Front.Api.V5.Exceptions.ConstraintViolationException: Cannot delete order with new or deleted items with some closed cafe sessions. Need all cafe sessions be opened.`

Если в заказ не добавлять продукт, то он удаляется без проблем.
Если в заказ добавить продукт, затем удалить из него этот продукт, то возникает та же самая ошибка.

Подскажите, пожалуйста, как правильно удалить заказ.

**Comment by novg** [comment]
Как же удалить заказ?

**Comment by novg** [comment]
```
[2020-09-09 16:09:31,938]  INFO [ 3] - Deleting order error: Resto.Front.Api.V5.Exceptions.ConstraintViolationException: Cannot delete order with new or deleted items with some closed cafe sessions. Need all cafe sessions be opened.

Server stack trace: 
   в Resto.Front.Api.V5.OperationService.CheckOrderCanBeDeleted(IBaseOrder order, IUser user) в H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Resto.Front.Api\V5\OperationService.cs:строка 789
   в Resto.Front.Api.V5.OperationService.DeleteOrder(IUser user, IBaseOrderEntity order) в H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Resto.Front.Api\V5\OperationService.cs:строка 742
   в Resto.Front.Api.V5.OperationService.Resto.Front.Api.V5.IOperationService.DeleteOrder(ICredentials credentials, IOrder order) в H:\BuildAgent\work\release-installer\dev\iikoFront.Net\Resto.Front.Api\V5\Operations.g.cs:строка 2479
   в System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   в System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   в System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   в System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   в Resto.Front.Api.V5.IOperationService.DeleteOrder(ICredentials credentials, IOrder order)
   в KrasPlugin.Services.OrderService.Delete(IOrder order) в C:\Users\a.novgorodsky\source\repos\KrasPlugin\Services\OrderService.cs:строка 129
   в KrasPlugin.Controllers.OrdersController.Delete(Guid id) в C:\Users\a.novgorodsky\source\repos\KrasPlugin\Controllers\OrdersController.cs:строка 192
```

**Comment by letolika** [comment]
Добрый день.
Это by design поведение iikoFront. То же самое будет, если создать заказ через UI, добавить в него блюдо и сразу же его удалить, даже не печатая на кухню. Удаление такого заказа потребует открытой кассовой смены. Сделано было для того, чтобы можно было строить отчеты, привязанные к кассовым сменам, и видеть, какие заказы и какие блюда в них были удалены. Но в Api.V6 был добавлен метод [`DeleteOrderAndHideItemsFromOlap`](https://iiko.github.io/front.api.sdk/v6/html/M_Resto_Front_Api_IOperationService_DeleteOrderAndHideItemsFromOlap.htm), не требующий открытой кассовой смены, если в заказе все блюда удалены без списания. Решение здесь — перейти на актуальную версию Api.V6, или открывать кассовую смену для удаления таких заказов старым методом.

**Comment by novg** [comment]
Спасибо!

**Comment by novg** [comment]
Подскажите, пожалуйста, как открыть кассовую смену из плагина.

**Comment by letolika** [comment]
#165

**Comment by novg** [comment]
Спасибо!
